### ISSUE TITLE
invalid mnemonic

### ISSUE THREAD

**Issue by bruno77689** [ivekivek/pancakeswap-bot#2]
**When i run the code i get the follow error of invalid mnemonic. The mnemonic is the private key, correct?**

Thanks for any help

```
C:\Users\bruno1\Downloads\pancakeswap-bot-main1\pancakeswap-bot-main>node bot
C:\Users\bruno1\Downloads\pancakeswap-bot-main1\pancakeswap-bot-main\node_modules\@ethersproject\hdnode\lib\index.js:270
        throw new Error("invalid mnemonic");
        ^

Error: invalid mnemonic
    at mnemonicToEntropy (C:\Users\bruno1\Downloads\pancakeswap-bot-main1\pancakeswap-bot-main\node_modules\←[4m@ethersproject←[24m\hdnode\lib\index.js:270:15)
    at Function.HDNode.fromMnemonic (C:\Users\bruno1\Downloads\pancakeswap-bot-main1\pancakeswap-bot-main\node_modules\←[4m@ethersproject←[24m\hdnode\lib\index.js:219:38)
    at Function.Wallet.fromMnemonic (C:\Users\bruno1\Downloads\pancakeswap-bot-main1\pancakeswap-bot-main\node_modules\←[4m@ethersproject←[24m\wallet\lib\index.js:238:43)
    at Object.<anonymous> (C:\Users\bruno1\Downloads\pancakeswap-bot-main1\pancakeswap-bot-main\bot.js:17:30)
←[90m    at Module._compile (node:internal/modules/cjs/loader:1109:14)←[39m
←[90m    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)←[39m
←[90m    at Module.load (node:internal/modules/cjs/loader:989:32)←[39m
←[90m    at Function.Module._load (node:internal/modules/cjs/loader:829:14)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)←[39m
←[90m    at node:internal/main/run_main_module:17:47←[39m
```

**Comment by car-mrazomor** [comment]
> **When i run the code i get the follow error of invalid mnemonic. The mnemonic is the private key, correct?**
> 
> 
> 
> Thanks for any help
> 
> 
> 
> ```
> 
> C:\Users\bruno1\Downloads\pancakeswap-bot-main1\pancakeswap-bot-main>node bot
> 
> C:\Users\bruno1\Downloads\pancakeswap-bot-main1\pancakeswap-bot-main\node_modules\@ethersproject\hdnode\lib\index.js:270
> 
>         throw new Error("invalid mnemonic");
> 
>         ^
> 
> 
> 
> Error: invalid mnemonic
> 
>     at mnemonicToEntropy (C:\Users\bruno1\Downloads\pancakeswap-bot-main1\pancakeswap-bot-main\node_modules\←[4m@ethersproject←[24m\hdnode\lib\index.js:270:15)
> 
>     at Function.HDNode.fromMnemonic (C:\Users\bruno1\Downloads\pancakeswap-bot-main1\pancakeswap-bot-main\node_modules\←[4m@ethersproject←[24m\hdnode\lib\index.js:219:38)
> 
>     at Function.Wallet.fromMnemonic (C:\Users\bruno1\Downloads\pancakeswap-bot-main1\pancakeswap-bot-main\node_modules\←[4m@ethersproject←[24m\wallet\lib\index.js:238:43)
> 
>     at Object.<anonymous> (C:\Users\bruno1\Downloads\pancakeswap-bot-main1\pancakeswap-bot-main\bot.js:17:30)
> 
> ←[90m    at Module._compile (node:internal/modules/cjs/loader:1109:14)←[39m
> 
> ←[90m    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)←[39m
> 
> ←[90m    at Module.load (node:internal/modules/cjs/loader:989:32)←[39m
> 
> ←[90m    at Function.Module._load (node:internal/modules/cjs/loader:829:14)←[39m
> 
> ←[90m    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)←[39m
> 
> ←[90m    at node:internal/main/run_main_module:17:47←[39m
> 
> ```

For this you need to use Send Phrase from your wallet, not private key.
